{{
    config(
        materialized = 'table'
    )
}}

-- Conformed date dimension.
-- GENERATED, not sourced -- no ref() or source() appears here by design.
-- Daily grain, contiguous, whole calendar years: all three are hard
-- requirements of Power BI's "Mark as Date Table" and of DAX time
-- intelligence. The fact table is monthly; the dimension is not.
-- Range is set by date_spine_start / date_spine_end in dbt_project.yml,
-- padded to whole calendar years beyond the fact table's data.

with digits as (

    select 0 as n
    union all select 1
    union all select 2
    union all select 3
    union all select 4
    union all select 5
    union all select 6
    union all select 7
    union all select 8
    union all select 9

),

day_offsets as (

    -- 10 x 10 x 10 x 10 = 10,000 sequential integers (0-9999),
    -- generated by place-value weighting. ~27 years of daily rows;
    -- the WHERE clause below trims to the configured range.
    select
        d1.n + (d2.n * 10) + (d3.n * 100) + (d4.n * 1000) as day_offset
    from digits as d1
    cross join digits as d2
    cross join digits as d3
    cross join digits as d4

),

date_spine as (

    select
        dateadd(
            day,
            day_offset,
            cast('{{ var("date_spine_start") }}' as date)
        ) as full_date
    from day_offsets
    where day_offset <= datediff(
        day,
        cast('{{ var("date_spine_start") }}' as date),
        cast('{{ var("date_spine_end") }}' as date)
    )

)

select
    -- Smart surrogate key: YYYYMMDD as int. Cheap to join, and unlike
    -- loan_key the value is readable, which makes join bugs obvious.
    cast(
        (year(full_date) * 10000)
        + (month(full_date) * 100)
        + day(full_date)
    as int) as date_key,

    full_date,

    year(full_date) as [year],
    datepart(quarter, full_date) as [quarter],

    cast(year(full_date) as varchar(4))
        + ' Q'
        + cast(datepart(quarter, full_date) as varchar(1)) as year_quarter,

    month(full_date) as month_number,

    -- datename() returns nvarchar(30), which Fabric Warehouse cannot
    -- persist as a column type -- cast to varchar.
    cast(datename(month, full_date) as varchar(20)) as month_name,

    -- YYYY-MM sorts correctly as text; 'Mar 2019' does not.
    cast(year(full_date) as varchar(4))
        + '-'
        + right('0' + cast(month(full_date) as varchar(2)), 2) as year_month,

    -- Period-boundary flag for closing-balance logic.
    -- Tomorrow in a different month means today is month end.
    cast(
        case
            when month(dateadd(day, 1, full_date)) <> month(full_date) then 1
            else 0
        end
    as bit) as is_month_end

from date_spine